services:
  - type: web
    name: ai-interview-question-generator
    env: python
    region: ohio
    buildCommand: bash ./build.sh
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: USE_MODELS
        value: false
      - key: MODEL_CACHE_DIR
        value: /tmp/models
      - key: RENDER
        value: true
      - key: DATABASE_URL
        sync: false  # You'll need to manually set this to your Supabase PostgreSQL connection string
      - key: SUPABASE_URL
        sync: false  # You'll set this manually in the Render dashboard
      - key: SUPABASE_KEY
        sync: false  # You'll set this manually in the Render dashboard
    plan: free
